### ISSUE TITLE
user password

### ISSUE THREAD

**Issue by pmsg863** [maasdi/vertx-web#1]
Hi Maas:
    I'm am new man for vertx and English, I deploy Verticle to vertx was successful, I can open the index in browser,but i can't login.
    i debug the programer,tracking the SecurityHandler,I do not know much about MD5,Can you tell me the password >.< Thanks.

-- admin : password
insert into user values ('admin', '5B844DDCB549E9DF29A7116C38B585FE452A5E7A0352102E984E1B793F44419B6BAC8246EA19F2F3618AE29AF6F015889A18D41BD038707C1017AFCCF70CE263', 'C7AD44CBAD762A5DA0A452F9E854FDC1E0E7A52A38015F23F3EAB1D80B931DD472634DFAC71CD34EBC35D16AB7FB8A90C81F975113D6C7538DC69DD8DE9077EC', 'Super', 'Admin', 'At main office');
-- jhon : password
insert into user values ('jhon', '42F2E57DB605380D4ED651E390B08FCAC9CF29F42E523A07FC3FB0B73DCF3D813C164F6F75B5508DCF121895692DC7BE438CA5860C354073C95EC55B93CFB35D', '74591AF8230F8D40BCC8143DC743B5AB0A76FADD63D2E7BB21D570A265C49DDD6E3FCFF0E7BEC5BF0C676F3C38A76283D437656CA25F29173721D0219CF7A5A8', 'Jhon', 'Doe', '21st Street');

**Comment by maasdi** [comment]
Hi,

If you run sql scripts from scripts.sql file correctly, you should be able to login with two test users :
1. username = admin, password = password
2. username = jhon, password = password

#Maas
